name: OpenTofu Preview

on: 
    pull_request:
        branches:
            - master

jobs:
    preview: 
        name: Plan OpenTofu Changes in changed Stacks
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            pull-requests: write
            checks: read

        steps:
            # Checkout the repo
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}
                fetch-depth: 0
            # install tooling
            - name: Install Terramate
              uses: terramate-io/terramate-actions@v2
            - name: Install asdf
              uses: asdf-vm/actions/setup@v3
            - name: Install OpenTofu with asdf
              run: |
                sdf install opentofu
            - name: List Changed Stacks
              run: terramate list --changed
            - name: Run Opentofu init
              run: terramate run -- tofu init
            - name: Run Opentofu plan
              run: terramate plan --tofu plan

